server:
  port: 9411
spring:
  application:
    name: kindergarten-zipkin-server
  sleuth:
    enabled: false #表示当前程序不使用sleuth
#zipkin数据保存到数据库中需要进行如下配置
zipkin:
  storage:
    strict-trace-id: ${STRICT_TRACE_ID:true}
    search-enabled: ${SEARCH_ENABLED:true}
    type: ${STORAGE_TYPE:mysql} #表示zipkin数据存储方式是mysql
    mysql:
      jdbc-url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/ag_zipkin}
      host: ${MYSQL_HOST:localhost}
      port: ${MYSQL_TCP_PORT:3306}
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:root}
      db: ${MYSQL_DB:ag_zipkin}
      max-active: ${MYSQL_MAX_CONNECTIONS:10}
      use-ssl: ${MYSQL_USE_SSL:false}
  collector:
    # RabbitMQ server address list (comma-separated list of host:port)
    addresses: ${RABBIT_ADDRESSES:192.168.0.108:5673}
    concurrency: ${RABBIT_CONCURRENCY:1}
    # TCP connection timeout in milliseconds
    connection-timeout: ${RABBIT_CONNECTION_TIMEOUT:60000}
    password: ${RABBIT_PASSWORD:guest}
    queue: ${RABBIT_QUEUE:zipkin}
    username: ${RABBIT_USER:guest}
    virtual-host: ${RABBIT_VIRTUAL_HOST:/}
    useSsl: ${RABBIT_USE_SSL:false}

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    prefer-ip-address: true #注册中心优先显示ip(true开启)
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #该配置项作用:注册中心显示该服务运行的服务器ip和端口
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 10*1000 #10s清理无效服务
  client:
    serviceUrl:
      defaultZone: http://zc:zc@${eureka.host:discovery1}:${eureka.port:8063}/eureka/,http://zc:zc@${eureka.host2:discovery2}:${eureka.port2:8064}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false