spring:
  application:
      name: kindergarten-admin-server
  security:
      basic:
      enabled: true #开启http认证
      user:
        name: zc
        password: zc
server:
    port: 8764 #启动端口

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    prefer-ip-address: true #注册中心优先显示ip(true开启)
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #该配置项作用:注册中心显示该服务运行的服务器ip和端口
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 10*1000 #10s清理无效服务
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://zc:zc@${eureka.host:discovery1}:${eureka.port:8066}/eureka/,http://zc:zc@${eureka.host2:discovery2}:${eureka.port2:8067}/eureka/


